create table AIRPORT (CODE varchar(255) not null, CITY varchar(255),NAME varchar(255), primary key (CODE));
create table FLIGHT (ID integer generated by default as identity (start with 1), ARRIVAL_TIME timestamp, DEPARTURE_TIME timestamp, MILES integer, NUMBER varchar(255), SEATS_AVAILABLE integer, FROM_AIRPORT_CODE varchar(255) not null, TO_AIRPORT_CODE varchar(255) not null, primary key (ID));
create table TICKET (id integer generated by default as identity (start with 1), ISSUE_DATE date, numberOfSeats integer not null, reservationName varchar(255), FLIGHT_ID integer not null, primary key (id));

ALTER TABLE TICKET ADD CONSTRAINT fk_ticket_flight FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT;

ALTER TABLE FLIGHT ADD CONSTRAINT fk_flight_from_airport FOREIGN KEY (FROM_AIRPORT_CODE) REFERENCES AIRPORT;
ALTER TABLE FLIGHT ADD CONSTRAINT fk_flight_to_airport FOREIGN KEY (TO_AIRPORT_CODE) REFERENCES AIRPORT;
