CREATE TABLE AIRPORT (
  CODE VARCHAR(30) PRIMARY KEY,
  NAME  VARCHAR(30),
  CITY  VARCHAR(80)
);

CREATE TABLE FLIGHT(
	ID BIGINT IDENTITY PRIMARY KEY,
	NUMBER VARCHAR(30),
	DEPARTURE_TIME TIMESTAMP,
	ARRIVAL_TIME TIMESTAMP,
	MILES INTEGER,
	FROM_AIRPORT_CODE VARCHAR(30),
	TO_AIRPORT_CODE VARCHAR(30),
	SEATS_AVAILABLE INTEGER
);

ALTER TABLE FLIGHT ADD CONSTRAINT fk_flight_from_airport FOREIGN KEY (FROM_AIRPORT_CODE) REFERENCES AIRPORT (code);
ALTER TABLE FLIGHT ADD CONSTRAINT fk_flight_to_airport FOREIGN KEY (TO_AIRPORT_CODE) REFERENCES AIRPORT (code);
